#
# hugo-deploy.yaml
# Archivo de configuraci√≥n de GitHub Actions para construir y desplegar el sitio web con Hugo y AWS S3
#

name: "Hugo Deploy"

on:
  push:
    paths:
      - "Blog de Juanje/**"

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clonar repositorio"
        uses: actions/checkout@v3
      - name: "Configurar credenciales AWS CLI"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "latest"
          extended: true
      - name: "Build"
        run: |
          cd "Blog de Juanje"
          hugo --minify
          pwd
          ls -la